### ISSUE TITLE
License: Which version of Artistic?

### ISSUE THREAD

**Issue by sebix** [dave-theunsub/thunar-sendto-clamtk#1]
The License file says:

> the "Artistic License". 

but which version? 1.0, 1.0 (Perl), 1.0 w/clause 8, 2.0 or Clarified Artistic License?

**Comment by dave-theunsub** [comment]
I'll have to think about that one... Is there some context to this question or were you just curious?

respectfully
Dave M

**Comment by sebix** [comment]
I packaged the software for opensuse and I wanted to specify both
licenses correctly. spdx.org does not list an "artistic" license without
version. So it's unclear for both you and potential users.

**Comment by dave-theunsub** [comment]
Hi,

I do plan on doing more research.  In the meanwhile, check the
[LICENSE](https://github.com/dave-theunsub/thunar-sendto-clamtk/blob/da9f6dfbe0a44822cd68103a99c8f9aaf7dc1b20/LICENSE#L12) file.  You can use either Artistic *or* one of the GPLs.

respectfully
Dave M

**Comment by sebix** [comment]
Thanks. And yes I used GPL-1.0+ only now, because of the unclear other
license.

**Comment by dave-theunsub** [comment]
Cool, thanks for following up.  I'll close this for now, but will keep researching the Artistic licenses to be more specific.

respectfully
Dave M
