### ISSUE TITLE
Unable to install on debian bullseye (no support for deb format tar.zst)

### ISSUE THREAD

**Issue by theofficialgman** [dave-theunsub/thunar-sendto-clamtk#2]
Debian Bullseye and older distros do not support the ubuntu pushed tar.zst format for control and data files in debs.

The deb needs to be repackaged to support these distros either on an older version of ubuntu where this packaging was not he default (focal or older) or debian bullseye or older or disable it through flags appropriate for the buildsystem in use.

**Comment by Botspot** [comment]
This is the error users get: 
```
dpkg-deb: error: archive '/tmp/thunar-sendto-clamtk_0.08-1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
```

**Comment by dave-theunsub** [comment]
Hi, thanks @theofficialgman and @Botspot ,

I lost the Virtualbox Ubuntu image I was using and, of course, the information in it to build with gz. I did rebuild using `dpkg-buildpackage -us -uc -Zgzip`, which is what I think I did last time. It successfully built the deb, but I don't know if it'll work yet to fix this issue.

So, now I'm going to load Debian and test it.  Unless, of course, there's an easier way to test if I did this build correctly?

Thanks,
Dave M

**Comment by theofficialgman** [comment]
> So, now I'm going to load Debian and test it. Unless, of course, there's an easier way to test if I did this build correctly?

@dave-theunsub just extract the deb and view its contents. if the data and control files are tar.gz or tar.xz then all is good. I personally use the GUI tool ark to do that but `ar x filename.deb` works fine as well

**Comment by dave-theunsub** [comment]
Then it didn't work:

```
ar x thunar-sendto-clamtk_0.08-2_all.deb 

ls
debian-binary  control.tar.zst  data.tar.zst  thunar-sendto-clamtk_0.08-2_all.deb

file *
control.tar.zst:                     Zstandard compressed data (v0.8+), Dictionary ID: None
data.tar.zst:                        Zstandard compressed data (v0.8+), Dictionary ID: None
debian-binary:                       ASCII text
thunar-sendto-clamtk_0.08-2_all.deb: Debian binary package (format 2.0), with control.tar.zs, data compression zst
```

**Comment by dave-theunsub** [comment]
I tried again using `dpkg-buildpackage -us -uc -Zxz` and it seemed to work. Will test it on Debian first, and then replace the old deb with this.

**Comment by dave-theunsub** [comment]
Ok, give that a shot (0.08-2).  Going to have to rebuild the new nemo-sendto-clamtk as well for the same reason.

**Comment by theofficialgman** [comment]
Looks fine but in the future if you create a re-release either:
A: don't change the filename or
B: create a new release tag

what you did is upload a new deb to the original release where the tag does not match the version. At pi-apps we have an automatic update detection method for many of our apps (nearly 70 that support this mechanism) and it relies on a consistent versioning scheme for releases. Our CI checks for updates for all of these 70 apps, tests if the files actually exist (this part will fail for your app with what you have done and cause it to revert to the previous working version), tests if the application installs on our supported targets, and then automatically updates the repo (prompting users to update) if all passes.

I would prefer that one of those suggestions be implemented now if you could do so please. While we can make the updater for your application "fuzzy" (by processing the names of all release assets for the appropriate .deb regardless of the inconsistent naming scheme) it is not our preference to do so.

**Comment by dave-theunsub** [comment]
There's a new tag now.
